
POST {{baseUrl}}/sp/ApiMgmtMainSearch/queryasync HTTP/1.1
Authorization: Bearer {{authorization}}
content-type: application/json

{
    "RefCd": "CUSTNO",
     "Int": "2024",
    //   "Int":"8A3",
}
###