###
//Vendor
POST {{baseUrl}}/sp/GetLibRef/queryasyncnouser HTTP/1.1
Authorization: Bearer {{authorization}}
content-type: application/json

{
"RefType": "TADVendor",
"BitInd": null
}



###
//MnM
POST {{baseUrl}}/sp/GetLibRef/queryasyncnouser HTTP/1.1
Authorization: Bearer {{authorization}}
content-type: application/json

{
"RefType": "DirectorType",
"BitInd": null
}

###
POST {{baseUrl}}/sp/GetLibRef/queryasyncnouser HTTP/1.1
Authorization: Bearer {{authorization}}
content-type: application/json

{"RefType":"MEDIATYPE",
"BitInd":null
}
###



POST {{baseUrl}}/sp/GetLibRef/queryasyncnouser HTTP/1.1
Authorization: Bearer {{authorization}}
content-type: application/json

{"RefType":"BANK",
"BitInd":null
}
###



POST {{baseUrl}}/sp/GetLibRef/queryasyncnouser HTTP/1.1
Authorization: Bearer {{authorization}}
content-type: application/json

{"RefType":"MONTH",
"BitInd":null
}
###


POST {{baseUrl}}/sp/GetLibRef/queryasyncnouser HTTP/1.1
Authorization: Bearer {{authorization}}
content-type: application/json

{"RefType":"title",
"BitInd":null
}
###


POST {{baseUrl}}/sp/GetLibRef/queryasyncnouser HTTP/1.1
Authorization: Bearer {{authorization}}
content-type: application/json

{"RefType":"ProductCode",
"BitInd":null
}
###


POST {{baseUrl}}/sp/GetLibRef/queryasyncnouser HTTP/1.1
Authorization: Bearer {{authorization}}
content-type: application/json

{"RefType":"TXNSCHEMA",
"BitInd":null
}
###


POST {{baseUrl}}/sp/GetLibRef/queryasyncnouser HTTP/1.1
Authorization: Bearer {{authorization}}
content-type: application/json

{"RefType":"PYMTTERM",
"BitInd":null
}
###

//


POST {{baseUrl}}/sp/GetLibRef/queryasyncnouser HTTP/1.1
Authorization: Bearer {{authorization}}
content-type: application/json

{"RefType":"EventType",
"BitInd":null
}
###